### ISSUE TITLE
key error in interpreter

### ISSUE THREAD

**Issue by AhmedAnsari** [amritasaha1812/CSQA_NPI#3]
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    main()
  File "train.py", line 156, in main
    train_model.train()
  File "train.py", line 141, in train
    sum_batch_loss = sum(self.perform_training(train_batch_dict))
  File "train.py", line 112, in perform_training
    answer = map(self.interpreter.execute_multiline_program,data_for_interpreter)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 53, in execute_multiline_program
    target_value = self.execute_singleline_program(program_type, argument_values)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 61, in execute_singleline_program
    func = self.map_program_to_func[program_type]
KeyError: 'map_oper_ints'

**Comment by AhmedAnsari** [comment]
When I ran again, the error did not appear.
Mostly i think one of the program type is not taken care of in the program table. so whenever during training instance, if that program type(mostly none) is samped, error appears

**Comment by AhmedAnsari** [comment]
**For debugging I printed program_type, argument_values to understand the error. I got the following output.**

**_program_type: select_oper_max, 	 argument_values: ['', '', '']_**
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    main()
  File "train.py", line 157, in main
    train_model.train()
  File "train.py", line 142, in train
    sum_batch_loss = sum(self.perform_training(train_batch_dict))
  File "train.py", line 112, in perform_training
    answer = map(self.interpreter.execute_multiline_program,data_for_interpreter)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 56, in execute_multiline_program
    target_value = self.execute_singleline_program(program_type, argument_values)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 67, in execute_singleline_program
    return func(argument_values)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 157, in execute_select_oper_max
    keys = tuple_map1.keys()
AttributeError: 'str' object has no attribute 'keys'

**Comment by AhmedAnsari** [comment]
Here is a more verbose output from another run:

**variable_value_table [['' '' '' '' '' '' '' '' '' '']
 [u'Q282019' None None None None None None None None None]
 [u'P364' None None None None None None None None None]
 [u'Q7210356' None None None None None None None None None]
 [None None None None None None None None None None]
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '' '' '']]
argument_type_id [7 7 0]
argument_table_index [0 0 8]
program_type: map_oper_ints, 	 argument_values: ['', '', '']**
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    main()
  File "train.py", line 157, in main
    train_model.train()
  File "train.py", line 142, in train
    sum_batch_loss = sum(self.perform_training(train_batch_dict))
  File "train.py", line 112, in perform_training
    answer = map(self.interpreter.execute_multiline_program,data_for_interpreter)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 63, in execute_multiline_program
    target_value = self.execute_singleline_program(program_type, argument_values)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 73, in execute_singleline_program
    func = self.map_program_to_func[program_type]
KeyError: 'map_oper_ints'

**Comment by AhmedAnsari** [comment]
# Explanation:
I think I have figured out why this happens. Basically initially only ERCI can be populated and if a program that uses an argument other than ERCI is sampled, then since the no variable exists w.r.t the programs aruments, the interpreter cannot execute.

# Solution:
we need to penalize the agent by giving negative reward for all these cases when it tries to sample from empty tables. @amritasaha1812  please verify this.

**Comment by AhmedAnsari** [comment]
Bug Solved. Above fix solves this bug and bug #4
