### ISSUE TITLE
accessing None from variable_value_table

### ISSUE THREAD

**Issue by AhmedAnsari** [amritasaha1812/CSQA_NPI#4]
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    main()
  File "train.py", line 157, in main
    train_model.train()
  File "train.py", line 142, in train
    sum_batch_loss = sum(self.perform_training(train_batch_dict))
  File "train.py", line 112, in perform_training
    answer = map(self.interpreter.execute_multiline_program,data_for_interpreter)
  File "/Users/ghulam/Documents/Work@IBM/CODE/CSQA_NPI/CSQA_NPI/code/NPI/interpreter.py", line 51, in execute_multiline_program
    raise Exception('')
Exception

**Comment by AhmedAnsari** [comment]
fix for bug #3 fixed this bug too as this exception was incorrectly being raised to prevent bug #3
